name: release
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Fluent CI CLI
        uses: fluentci-io/setup-fluentci@v4

      - name: Setup Fluent CI Engine CLI
        run: |
          wget https://github.com/fluentci-io/fluentci-engine/releases/download/v0.2.5/fluentci-engine_v0.2.5_x86_64-unknown-linux-gnu.tar.gz
          tar xvf fluentci-engine_v0.2.5_x86_64-unknown-linux-gnu.tar.gz
          sudo mv fluentci-engine /usr/local/bin

      - name: Add wasm32-unknown-unknown target
        run: |
          fluentci-engine call -m $MODULE -- \
          target_add wasm32-unknown-unknown

      - name: Build
        run: |
          fluentci-engine call -m $MODULE -- \
          build \
          --target wasm32-unknown-unknown \
          --release
          ls -ltr target/wasm32-unknown-unknown/release

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Upload release
        run: |
          export FILE=/app/plugin/target/wasm32-unknown-unknown/release/rust.wasm
          fluentci run github_pipeline release_upload
        env:
          TAG: ${{ env.RELEASE_VERSION }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
